### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by smersh1307n2** [ansiboy/ALinq#2]
How to make that some types of data, for example Guid in SQL query always were in the form of parameters?

Request for a view
SELECT t0.ID, t0.F1, t0.F2 AS DATETIME, t0.F3
FROM NEW_TABLE AS t0
WHERE a59f2561-b929-402a-bb7e-862f5be7cc8b = t0.ID
Causes an error.

**Comment by ansiboy** [comment]
specify type of the column in database.
```csharp

[Column(Storage = "_Id", DbType = "char(36)", IsPrimaryKey = true)]
public Guid Id
{
	get
	{
		return _Id;
	}
	set
	{
		if ((_Id != value))
		{
			OnIdChanging(value);
			SendPropertyChanging();
			_Id = value;
			SendPropertyChanged("Id");
			OnIdChanged();
		}
	}
}
```

The database  column data type can be string or binary data type

**Comment by smersh1307n2** [comment]
I tried to change the method
Internal override DBTypeCategory Category
      get
            {
                Switch ((FbDbType) SqlDbType)
                {
   ...
                 Case FbDbType.Guid:
                        // return DBTypeCategory.Text;
                        Return DBTypeCategory.Binary;
...
but didn't help. I am afraid not to understand without your help to me.
I changed ALinq.Firebird for operation with Firebird 3.0. Also I attached the new FirebirdWPF project for the test. If  group  column "ID" in RadGridView that we receive an error because of what in the request of Guid generated by SQL is added in the form of string but not parameter.Approximately too most it turns out in case of group of the column "DATETIME", only here as result nenichy doesn't return. 
Link to the project:
https://cloud.mail.ru/public/2mFa/1KNZZU7JU

**Comment by smersh1307n2** [comment]
Until the Problem was solved in the following way - in the method
ExtractParameter private SqlExpression(SqlExpression expr)
replaced 
var pName = sqlIdentity.ParameterPrefix + "x" + (parameters.Count + 1);
on
var pName = sqlIdentity.ParameterPrefix + "pt" + (parameters.Count + 1);
